// Code generated by protoc-gen-go. DO NOT EDIT.
// source: codec/jsonpbrpc/envelope.proto

/*
Package jsonpbrpc is a generated protocol buffer package.

It is generated from these files:
	codec/jsonpbrpc/envelope.proto

It has these top-level messages:
	Request
	Response
*/
package jsonpbrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	ServiceMethod    *string `protobuf:"bytes,1,opt,name=service_method,json=serviceMethod" json:"service_method,omitempty"`
	Seq              *uint64 `protobuf:"fixed64,2,opt,name=seq" json:"seq,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetServiceMethod() string {
	if m != nil && m.ServiceMethod != nil {
		return *m.ServiceMethod
	}
	return ""
}

func (m *Request) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

type Response struct {
	ServiceMethod    *string `protobuf:"bytes,1,opt,name=service_method,json=serviceMethod" json:"service_method,omitempty"`
	Seq              *uint64 `protobuf:"fixed64,2,opt,name=seq" json:"seq,omitempty"`
	Error            *string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetServiceMethod() string {
	if m != nil && m.ServiceMethod != nil {
		return *m.ServiceMethod
	}
	return ""
}

func (m *Response) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *Response) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "jsonpbrpc.Request")
	proto.RegisterType((*Response)(nil), "jsonpbrpc.Response")
}

func init() { proto.RegisterFile("codec/jsonpbrpc/envelope.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0xce, 0x4f, 0x49,
	0x4d, 0xd6, 0xcf, 0x2a, 0xce, 0xcf, 0x2b, 0x48, 0x2a, 0x2a, 0x48, 0xd6, 0x4f, 0xcd, 0x2b, 0x4b,
	0xcd, 0xc9, 0x2f, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0xcb, 0x28, 0x39,
	0x71, 0xb1, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xa9, 0x72, 0xf1, 0x15, 0xa7, 0x16,
	0x95, 0x65, 0x26, 0xa7, 0xc6, 0xe7, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0xf1, 0x42, 0x45, 0x7d, 0xc1, 0x82, 0x42, 0x02, 0x5c, 0xcc, 0xc5, 0xa9, 0x85, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x6c, 0x41, 0x20, 0xa6, 0x52, 0x24, 0x17, 0x47, 0x50, 0x6a, 0x71, 0x41,
	0x7e, 0x5e, 0x71, 0x2a, 0xd9, 0x86, 0x08, 0x89, 0x70, 0xb1, 0xa6, 0x16, 0x15, 0xe5, 0x17, 0x49,
	0x30, 0x83, 0xd5, 0x43, 0x38, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xe8, 0xd2, 0x5c, 0xca,
	0x00, 0x00, 0x00,
}
